version: "3.9"
services:
  web:
        build: .
        ports:
            - "8000:80"
        environment:
            - SERVER=192.168.0.105,9000
            - DATABASE_NAME=RegisterHouseIdentity
            - USER_BD=sa
            - USER_BD_PASSWORD=111
            
